version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: on-failure
    networks:
      - inception-nginx
    volumes:
      - wordpress:/var/www/wordpress
    env_file: ./.env
    depends_on:
      - wordpress


  mariadb:
    container_name: mariadb
    build:
      context:  requirements/mariadb
      dockerfile: Dockerfile
    restart:  unless-stopped
    networks:
      - inception-mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file: ./.env

    expose:
      - "3306"


  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - inception-wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file: ./.env
    depends_on:
      - mariadb

    expose: 
      - "9000"


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
    device: '/Users/login/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
    device: '/Users/login/data/mariadb'

networks:
  inception:
    driver: bridge