version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart:  always
    env_file: .env
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    networks:
      - inception
    volumes:
      - wp:/var/www/html/wordpress
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    hostname: localhost
    networks:
      - inception
    volumes:
      - wp:/var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"

  redis:
    container_name: redis
    build: requirements/bonus/redis
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  ftp-server:
    container_name: ftp-server
    build: requirements/bonus/ftp-server
    ports:
      - "21:21"
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - inception
    restart: always
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}
  
  adminer:
    container_name: adminer
    ports:
      - "9000:8080"
    image: adminer:4
    restart: unless-stopped
    networks:
      - inception
    depends_on:
      - mariadb
  
  portainer:
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    security_opt:
      - no-new-privileges:true

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db

networks:
  inception:
    driver: bridge